# Generated by Django 4.0.1 on 2022-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customers_colleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
