# Generated by Django 4.0.1 on 2022-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_cart_pri_alter_cart_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_track_id',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.TextField(default='****'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idpay_track_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.TextField(default='14/14/14 14:14:14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.TextField(default='14/14/14 14:14:14'),
            preserve_default=False,
        ),
    ]
