# Generated by Django 4.0.1 on 2022-06-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_payment_order_payment_bank_track_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
