# Generated by Django 4.0.1 on 2022-06-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'پرداخت انجام نشده است'), (2, 'پرداخت ناموفق بوده است'), (3, 'خطا رخ داده است'), (6, 'برگشت خورده سیستمی'), (7, 'انصراف از پرداخت'), (10, 'در انتظار تایید پرداخت'), (100, 'تراکنش تایید شده')]),
        ),
    ]
