# Generated by Django 4.0.1 on 2022-06-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_variable_price_options'),
        ('account', '0012_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variable_price'),
        ),
    ]
