from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

import account.views
import main.views
import product.views
import gallery.views
from . import views
from .views import payments_view, change_payment_status, view_order_details, dashbord_header, dashboard

name_app = "dashboard"
urlpatterns= [
    path("dashboard" , dashboard , name = "dashboard"),
    path("maincategory" , product.views.manage_main_category , name = "maincategory"),
    path("setmaincategory" , product.views.setmaincategory , name = "setmaincategory"),
    path("deletemaincategory" , product.views.deletemaincategory , name = "deletemaincategory"),
    path("subcategory" , product.views.manage_sub_category , name = "subcategory"),
    path("setsubcategory" , product.views.setsubcategory , name = "setsubcategory"),
    path("deletesubcategory" , product.views.deletesubcategory , name = "deletesubcategory"),
    path("treemenu" , product.views.manage_tree_menu , name = "treemenu"),
    path("deletetreemenu" , product.views.deletetreemenu , name = "deletetreemenu"),
    path("settreemenu" , product.views.settreemenu , name = "settreemenu"),
    path("menu" , product.views.manage_menu , name = "menu"),
    path("deletemenu" , product.views.deletemenu , name = "deletemenu"),
    path("setmenu" , product.views.setmenu , name = "setmenu"),
    path("submenu" , product.views.manage_sub_menu , name = "submenu"),
    path("deletesubmenu" , product.views.deletesubmenu , name = "deletesubmenu"),
    path("setsubmenu" , product.views.setsubmenu , name = "setsubmenu"),
    path("brand" , product.views.manage_brand , name = "brand"),
    path("deletebrand" , product.views.deletebrand , name = "deletebrand"),
    path("setbrand" , product.views.setbrand , name = "setbrand"),
    path("color" , product.views.manage_color , name = "color"),
    path("deletecolor" , product.views.deletecolor , name = "deletecolor"),
    path("setcolor" , product.views.setcolor , name = "setcolor"),
    path("warranty" , product.views.manage_warranty , name = "warranty"),
    path("deletewarranty" , product.views.deletewarranty , name = "deletewarranty"),
    path("setwarranty" , product.views.setwarranty , name = "setwarranty"),
    path("details" , product.views.manage_details , name = "details"),
    path("deletedetails" , product.views.deletedetails , name = "deletedetails"),
    path("setdetails" , product.views.setdetails , name = "setdetails"),
    path("valuedetails" , product.views.manage_value_details, name = "valuedetails"),
    path("deletevaluedetails" , product.views.deletevaluedetails, name = "deletevaluedetails"),
    path("setvaluedetails" , product.views.setvaluedetails, name = "setvaluedetails"),
    path("create_product" , product.views.create_product, name = "create_product"),
    path("images_upload" , gallery.views.upload_images , name = "images_upload"),
    path("show_images" , gallery.views.show_images , name = "show_images"),
    path("update_images" , gallery.views.update_images , name = "update_images"),
    path("del_images" , gallery.views.del_images , name = "del_images"),
    path("select_image" , gallery.views.select_image , name = "select_image"),
    path("select_multi_image" , gallery.views.select_multi_image , name = "select_multi_image"),
    path("show_products" , product.views.show_products , name = "show_products"),
    path("del_product" , product.views.del_product , name = "del_product"),
    path("update_product" , product.views.update_product , name = "update_product"),
    path("set_price/<int:product_id>" , product.views.set_price , name = "set_price"),
    path("update_price/" , product.views.update_price , name = "update_price"),
    path("del_price/" , product.views.del_price , name = "del_price"),
    path("list_price/" , product.views.list_price , name = "list_price"),
    path("variable/" , product.views.variable_ , name = "variable"),
    path("deletevariable/" , product.views.deletevariable , name = "deletevariable"),
    path("setvariable/" , product.views.setvariable , name = "setvariable"),
    path("allow_comment/" , product.views.check_comment_product , name = "allow_comment"),
    path("get_data_comment/" , product.views.get_data_comment , name = "get_data_comment"),
    path("change_show_comment/" , product.views.change_show_comment , name = "change_show_comment"),
    path("generator_page/" , views.generator_page , name = "generator_page"),
    path("delete_page/<int:page_id>" , views.delete_page , name = "delete_page"),
    path("update_page/" , views.update_page , name = "update_page"),
    path("update_footer/" , views.update_footer , name = "update_footer"),
    path("update_sub_footer/" , views.update_sub_footer , name = "update_sub_footer"),
    path("main_footer/" , views.main_footer_ , name = "main_footer"),
    path("delete_footer/<int:id_footer>" , views.delete_footer , name = "delete_footer"),
    path("delete_sub_footer/<int:id_sub_footer>" , views.delete_sub_footer , name = "delete_sub_footer"),
    path("delete_navbar_process/<int:navbar_id>" , views.delete_navbar_process , name = "delete_navbar_process"),
    path("sub_footer/" , views.sub_footer_ , name = "sub_footer"),
    path("set_logo/" , main.views.set_logo , name = "set_logo"),
    path("set_icon/" , main.views.set_icon , name = "set_icon"),
    path("navbar_process/" , views.manage_navbar_process , name = "navbar_process"),
    path("swiper/" , views.manage_swiper , name = "swiper"),
    path("delete_swiper/<int:swiper_id>" , views.delete_swiper , name = "delete_swiper"),
    path("update_swiper/" , views.update_swiper , name = "update_swiper"),
    path("update_navbar_process/" , views.update_navbar_process , name = "update_navbar_process"),
    path("blogs/" , views.blog_manager , name = "blogs"),
    path("delete_blogs/<int:blogs_id>", views.delete_blogs, name="delete_blogs"),
    path("update_blogs/" , views.update_blogs , name = "update_blogs"),
    path("category_blog/" , views.category_blog_manager , name = "category_blog"),
    path("update_category_blog/" , views.category_update_blogs , name = "update_category_blog"),
    path("delete_category_blogs/<int:catblogs_id>", views.category_delete_blogs, name="delete_category_blogs"),
    path("state/", account.views.state_manager, name="state"),
    path("update_state/" , account.views._update_state , name = "update_state"),
    path("delete_state/<int:id_state>" , account.views._delete_state , name = "delete_state"),
    path("city" , account.views.city_manager , name = "city"),
    path("delete_city/<int:id_city>" , account.views._delete_city , name = "delete_city"),
    path("update_city" , account.views._update_city , name = "update_city"),
    path("payments_view" , payments_view , name = "payments_view"),
    path("change_payment_status" , change_payment_status , name = "change_payment_status"),
    path("order_details/<str:uuid>" , view_order_details , name = "order_details"),
    path("dashbord_header" , dashbord_header , name = "dashbord_header"),
]