# Generated by Django 4.0.1 on 2022-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_product',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment_product',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
