# Generated by Django 4.0.1 on 2022-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment_product_show_alter_comment_product_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='product',
            name='meta_descriptions',
            field=models.CharField(default='توضیحات', max_length=500),
            preserve_default=False,
        ),
    ]
