# Generated by Django 4.0.1 on 2022-03-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_meta_title_product_meta_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable_price',
            options={'ordering': ['-discount']},
        ),
    ]
