# Generated by Django 4.0.1 on 2022-07-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_menu_options_remove_menu_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='link',
        ),
    ]
