# Generated by Django 4.0.1 on 2022-07-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_treemenu_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_product',
            name='sendtime',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
