# Generated by Django 4.0.1 on 2022-03-23 17:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='page_generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description_seo', models.TextField(max_length=450)),
                ('keywords_seo', models.CharField(max_length=150)),
                ('tags_seo', models.CharField(max_length=150)),
                ('text', tinymce.models.HTMLField()),
                ('image', models.ForeignKey(default=76, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='gallery.images')),
            ],
        ),
    ]
