# Generated by Django 4.0.1 on 2022-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='page_generator',
            name='title',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
