# Generated by Django 4.0.1 on 2022-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_main_footer_alter_page_generator_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_generator',
            name='title',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True),
        ),
    ]
