# Generated by Django 4.0.1 on 2022-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_page_generator_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_generator',
            name='url',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='page_generator',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
