# Generated by Django 4.0.1 on 2022-04-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_page_generator_url_alter_page_generator_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_generator',
            name='url',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True),
        ),
    ]
