# Generated by Django 4.0.1 on 2022-04-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_page_generator_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.main_footer')),
            ],
        ),
    ]
