# Generated by Django 4.0.1 on 2022-04-19 12:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('dashboard', '0007_sub_footer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('url', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('description_seo', models.TextField(max_length=450)),
                ('keywords_seo', models.CharField(max_length=150)),
                ('tags_seo', models.CharField(max_length=150)),
                ('text', tinymce.models.HTMLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category_blog')),
                ('image', models.ForeignKey(default=76, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='gallery.images')),
            ],
        ),
    ]
