# Generated by Django 4.0.1 on 2022-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('alt', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
